### ISSUE TITLE
brand_option MVA requires RANGE-QUERY

### ISSUE THREAD

**Issue by antage** [romul/spree-sphinx-search#2]
Sphinx 0.9.9, Spree 0.50, ruby-ee 1.8.7

При вызове `rake ts:index` выдается ошибка:

<pre>ERROR: source 'product_core_0': unexpected end of line in sql_attr_multi.
ERROR: index 'product_core': failed to configure some of the sources, will not index.</pre>

Ошибка появляется из-за двух строчек в конфиге sphinx-а:

<pre>sql_attr_multi = uint brand_option from ranged-query; SELECT DISTINCT p.id, ov.id FROM option_values AS ov LEFT JOIN option_types AS ot ON (ov.option_type_id = ot.id) LEFT JOIN option_values_variants AS ovv ON (ovv.option_value_id = ov.id) LEFT JOIN variants AS v ON (ovv.variant_id = v.id) LEFT JOIN products AS p ON (v.product_id = p.id) WHERE (ot.name = 'brand' AND p.id&gt;=$start AND p.id&lt;=$end);
sql_attr_multi = uint brand_option_facet from ranged-query; SELECT DISTINCT p.id, ov.id FROM option_values AS ov LEFT JOIN option_types AS ot ON (ov.option_type_id = ot.id) LEFT JOIN option_values_variants AS ovv ON (ovv.option_value_id = ov.id) LEFT JOIN variants AS v ON (ovv.variant_id = v.id) LEFT JOIN products AS p ON (v.product_id = p.id) WHERE (ot.name = 'brand' AND p.id&gt;=$start AND p.id&lt;=$end);
</pre>

Ошибка вызвана тем, что ranged-query требует два SQL-запроса: на получение пары (doc_id, uint_value) и на выборку минимального и максимального doc_id (`RANGE-QUERY`). В вышеуказанных запросах есть только первый запрос и нет второго.

Самое простое решение проблемы - это не использовать `:source => :ranged_query` в `has brand_sql`, а использовать просто `:source => :query`, тем более что использование `ranged-query` тут ничем не обоснованно (там нет больших выборок данных, а значит и нет смысла использовать `ranged-query`). Другой вариант - модифицировать запрос в `option_sql` и добавить `RANGE-QUERY`.

**Comment by antage** [comment]
Добавил патч - https://github.com/romul/spree-sphinx-search/pull/3

**Comment by antage** [comment]
Насчёт необоснованности `ranged-query` я возможно погорячился :)

**Comment by romul** [comment]
Насколько я помню, обоснованность хорошо проявляется, когда кол-во значений опций переваливает за полмиллиона. Но в любом случае спасибо за найденный баг. Честно говоря, на данный момент я чаще использую Solr, поэтому до сих пор не проверил обновление данного расширения под Spree 0.30+, которое было выполнено не вполне корректно. В оригинале, работающем под Spree 0.10-0.11 второй запрос 

```
SELECT IFNULL(MIN(`id`), 1), IFNULL(MAX(`id`), 1) FROM `products`
```

был: https://github.com/romul/spree-sphinx-search/commit/63e257305b5de115f055ff95a74780b02f8f6551#L9L51
и надо просто вернуть его на место.

**Comment by antage** [comment]
<pre>SELECT IFNULL(MIN(`id`), 1), IFNULL(MAX(`id`), 1) FROM `products`</pre>


С таким запросом мы сразу получим ошибку на postgresql, так как там нет функции `IFNULL`, вместо неё используется `COALESCE`.

**Comment by romul** [comment]
Ну да, для Spree всё-таки рекомендовано использовать MySQL. Хотя если ты фанат Postrges'а, то можно ведь добавить дополнительный if:

```
if (ActiveRecord::Base.connection.adapter_name == 'PostgreSQL')
  range_select = "что-то там для postgresql"
else
  range_select = "SELECT IFNULL(MIN(`id`), 1), IFNULL(MAX(`id`), 1) FROM `products`"
end
```

В общем жду тогда от тебя патч, годный для обеих СУБД.

**Comment by antage** [comment]
Патч - antage/spree-sphinx-search@37a3abebbb8e98f81cb1
RANGE-QUERY генерирует сам thinking_sphinx в зависимости от типа БД.
Набор товарных опций для индексации сделал расширяемый (по умолчанию пустой).
Пользователь сам сможет кастомизировать его декоратором:

<pre>Product.class_eval do
  self.indexed_options = [:brand, :color, :size]
end</pre>

**Comment by antage** [comment]
Fixed at @927644bb779861a4c9fa
